version: 0.1.0

scenario:
  ref: S129
  summary_dir: Results
  ll: ['copt']
  clusters: 16
  opts: [Co2L-Ep-24H-CCL]

plotting:
  map:
    figsize: [10, 10]
    boundaries: [5,15,46,55]
    p_nom:
      bus_size_factor: 5.e+4
      linewidth_factor: 3.e+3


  tech_colors:
    "onwind" : "#235ebc"
    "p_max" : "DarkCyan"
    "onshore wind" : "#235ebc"
    'offwind' : "#6895dd"
    'offwind-ac' : "#6895dd"
    'offshore wind' : "#6895dd"
    'offshore wind ac' : "#6895dd"
    'offwind-dc' : "#74c6f2"
    'offshore wind dc' : "#74c6f2"
    "hydro" : "#08ad97"
    "hydro+PHS" : "#08ad97"
    "PHS" : "#08ad97"
    "hydro reservoir" : "#08ad97"
    'hydroelectricity' : '#08ad97'
    "ror" : "#4adbc8"
    "run of river" : "#4adbc8"
    'solar' : "#f9d002"
    'solar PV' : "#f9d002"
    'solar thermal' : '#ffef60'
    'biomass' : '#0c6013'
    'solid biomass' : '#06540d'
    'biogas' : '#23932d'
    'waste' : '#68896b'
    'geothermal' : '#ba91b1'
    "OCGT" : "#d35050"
    "OCGT marginal" : "#d35050"
    "OCGT-heat" : "#d35050"
    "gas boiler" : "#d35050"
    "gas boilers" : "#d35050"
    "gas boiler marginal" : "#d35050"
    "gas-to-power/heat" : "#d35050"
    "gas" : "#d35050"
    "natural gas" : "#d35050"
    "CCGT" : "#b20101"
    "CCGT marginal" : "#b20101"
    "Nuclear" : "#ff9000"
    "Nuclear marginal" : "#ff9000"
    "nuclear" : "#ff9000"
    "coal" : "#707070"
    "Coal" : "#707070"
    "Coal marginal" : "#707070"
    "lignite" : "#9e5a01"
    "Lignite" : "#9e5a01"
    "Lignite marginal" : "#9e5a01"
    "Oil" : "#262626"
    "oil" : "#262626"
    "H2" : "#ea048a"
    "hydrogen storage" : "#ea048a"
    "Sabatier" : "#a31597"
    "methanation" : "#a31597"
    "helmeth" : "#a31597"
    "DAC" : "#d284ff"
    "co2 stored" : "#e5e5e5"
    "CO2 sequestration" : "#e5e5e5"
    "battery" : "#b8ea04"
    "battery storage" : "#b8ea04"
    "Li ion" : "#b8ea04"
    "BEV charger" : "#e2ff7c"
    "V2G" : "#7a9618"
    "transport fuel cell" : "#e884be"
    "retrofitting" : "#e0d6a8"
    "building retrofitting" : "#e0d6a8"
    "heat pumps" : "#ff9768"
    "heat pump" : "#ff9768"
    "air heat pump" : "#ffbea0"
    "ground heat pump" : "#ff7a3d"
    "power-to-heat" : "#a59e7c"
    "power-to-gas" : "#db8585"
    "power-to-liquid" : "#a9acd1"
    "Fischer-Tropsch" : "#a9acd1"
    "resistive heater" : "#aa4925"
    "water tanks" : "#401f75"
    "hot water storage" : "#401f75"
    "hot water charging" : "#351c5e"
    "hot water discharging" : "#683ab2"
    "CHP" : "#d80a56"
    "CHP heat" : "#d80a56"
    "CHP electric" : "#d80a56"
    "district heating" : "#93864b"
    "Ambient" : "#262626"
    "Electric load" : "#f9d002"
    "electricity" : "#f9d002"
    "Heat load" : "#d35050"
    "heat" : "#d35050"
    "Transport load" : "#235ebc"
    "transport" : "#235ebc"
    "lines" : "#70af1d"
    "transmission lines" : "#70af1d"
    "AC-AC" : "#70af1d"
    "AC line" : "#70af1d"
    "links" : "#8a1caf"
    "HVDC links" : "#8a1caf"
    "DC-DC" : "#8a1caf"
    "DC link" : "#8a1caf"
    "Regional" : "green"
    "DC" : "#8a1caf"
    "AC" : "#70af1d"
    "Flexibility" : "pink"
    "Shedding" : "grey"
    "Balance" : "grey"
    "No Shedding" : "red"
    "Grid" : "red"
    "Renewable Energy Cost" : "lime" 
    "Conventional Energy Cost" : "yellow"
    "Conventional Investments Cost" : "brown" 
    "Renewable Investments Cost" : "seagreen"
    "Flexibility Investments Cost" : "fuchsia"
    "1" : "black"
    "2" : "green"
    "3" : "blue"
    "4" : "purple"
    "5" : "red"
    "6" : "brown"
    "7" : "gray"
    "8" : "yellow"
    "0.01" : "black"
    "0.05" : "blue"
    "0.07" : "green"
    "0.1" : "red"
    "High SME Potential" : "red"
    "Long SME Duration" : "green"
    "Low SME Cost" : "purple"
    "Optimal SME Settings" : "green"
    "Pessimal SME Settings" : "red"
    "Sub-optimal SME Settings" : "purple"
    "No SME Flexibility" : "k"

